packages/shared/src/utils/tests/updateable.test.js, packages/shared/src/utils/updateable.js, packages/uploader/src/queue/tests/index.test.js
- proxy only on dev
- need to proxy new objects if they are added/pushed/etc during update
=> fix(shared): updateable fixes

.eslintrc.js, .storybook/main.js, cypress/integration/upload-preview/UploadPreview-clear-spec.js, cypress/integration/upload-preview/UploadPreview-simple-spec.js, guides/README.md, guides/UploadQueue.md, packages/ui/retry-hooks/RetryHooks.stories.js, packages/ui/shared/src/index.js, packages/ui/shared/src/types.js, packages/ui/shared/src/useWithForwardRef.js, packages/ui/upload-button/src/asUploadButton.js, packages/ui/upload-preview/README.md, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/upload-preview/src/UploadPreview.js, packages/ui/upload-preview/src/tests/UploadPreview.test.js, packages/ui/upload-preview/src/tests/usePreviewsLoader.test.js, packages/ui/upload-preview/src/types.js, packages/ui/upload-preview/src/usePreviewsLoader.js, packages/ui/upload-preview/types/index.d.ts, packages/ui/upload-url-input/src/UploadUrlInput.js, packages/ui/upload-url-input/src/types.js, packages/ui/upload-url-input/types/index.d.ts
* add ability to clear previews
* get access to previews array (show count)
* docs: upload queue guide
=> feat(upload-preview): preview methods - clear

cypress/integration/tus-uploady/TusUploady-simple-spec.js, cypress/integration/upload-preview/UploadPreview-crop-spec.js, cypress/integration/uploadFile.js, packages/tus-sender/README.md, packages/tus-sender/src/tusSender/initTusUpload/createUpload.js, packages/ui/tus-uploady/README.md, packages/ui/tus-uploady/TusUploady.stories.js, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/upload-preview/src/UploadPreview.js, packages/ui/upload-preview/src/tests/UploadPreview.test.js
fix(upload-preview): isFallback isnt passed to preview
fix(tus-sender): include custom headers from destination. fixes #60
=> 0.3.0 fixes

packages/ui/upload-button/src/asUploadButton.js, packages/ui/upload-drop-zone/README.md, packages/ui/upload-drop-zone/UploadDropZone.stories.js, packages/ui/upload-drop-zone/package.json, packages/ui/upload-drop-zone/src/UploadDropZone.js, packages/ui/upload-drop-zone/src/types.js, packages/ui/upload-drop-zone/types/index.d.ts
=> feat: upload drop zone extraProps prop

packages/core/life-events/package.json, packages/core/simple-state/src/tests/createState.test.js, packages/core/simple-state/src/utils.js, packages/core/uploader/package.json, packages/native/native-uploady/package.json, packages/ui/chunked-uploady/package.json, packages/ui/retry-hooks/package.json, packages/ui/tus-uploady/package.json, packages/ui/upload-button/package.json, packages/ui/upload-drop-zone/package.json, packages/ui/uploady/package.json
=> fix:  simple state File object not available in ssr

cypress/integration/uploady/uploady-filesParamName-spec.js, packages/core/uploader/src/tests/utils.test.js, packages/core/uploader/src/utils.js, packages/ui/uploady/Uploady.stories.js
=> fix: files param name not respected

packages/core/shared/src/batchItem.js, packages/core/shared/src/types.js, packages/core/shared/types/index.d.ts, packages/core/uploader/README.md, packages/core/uploader/src/queue/processFinishedRequest.js, packages/core/uploader/src/queue/tests/processFinishedRequest.test.js, packages/ui/uploady/README.md
=> Add status code to item

cypress/integration/upload-button/UploadButton-group-spec.js, cypress/integration/uploady/Uploady-customResponseFormat-spec.js, packages/core/mock-sender/src/mockSender.js, packages/core/mock-sender/src/tests/mockSender.test.js, packages/core/sender/src/types.js, packages/core/sender/src/xhrSender/tests/xhrSender.test.js, packages/core/sender/src/xhrSender/xhrSender.js, packages/core/sender/types/index.d.ts, packages/core/shared/src/request/parseResponseHeaders.js, packages/core/shared/src/types.js, packages/core/shared/types/index.d.ts, packages/core/uploader/README.md, packages/core/uploader/src/batchItemsSender.js, packages/ui/uploady/README.md, packages/ui/uploady/Uploady.stories.js
- docs, ut, spec
- added to mock sender as well
=>  feat: formatServerResponse sender param

bundle.config.js, packages/core/shared/src/logger.js, packages/core/shared/src/utils/isProduction.js
=> fix: handle process.env not present

cypress/integration/tus-uploady/TusUploady-send-data-spec.js, cypress/integration/tus-uploady/TusUploady-simple-spec.js, packages/core/chunked-sender/src/chunkedSender/processChunks.js, packages/core/chunked-sender/src/chunkedSender/tests/processChunks.test.js, packages/ui/tus-uploady/TusUploady.stories.js
ensure the offset is added to the loaded calculation so resume is also reflected in progress
fixes #147
=> fix: progress for chunked upload with first chunk offset

packages/ui/shared/types/index.d.ts, packages/ui/shared/types/index.test-d.tsx
added typing to support async version of hook
fixes #158
=> fix: useRequestPreSend async typing

packages/ui/shared/types/index.d.ts, packages/ui/shared/types/index.test-d.tsx
=> fix: typings for useRequestPreSend

packages/core/chunked-sender/src/chunkedSender/processChunks.js, packages/core/chunked-sender/src/chunkedSender/sendChunk.js, packages/core/chunked-sender/src/chunkedSender/tests/processChunks.test.js, packages/core/chunked-sender/src/chunkedSender/tests/sendChunk.test.js, packages/core/chunked-sender/src/chunkedSender/types.js, packages/core/chunked-sender/src/types.js, packages/core/chunked-sender/types/index.d.ts, packages/core/tus-sender/src/tusSender/handleEvents.js, packages/core/tus-sender/src/tusSender/tests/hadnleEvents.test.js
chunk start event:
- rename chunkCount to remainingCount
- add totalCount
=> feat!: chunked start event totalCount and remainingCount

babel.config.js, packages/core/shared/src/utils/isProduction.js
=> fix: process is not defined

babel.config.js, packages/core/shared/src/logger.js, packages/core/shared/src/tests/logger.test.js
to avoid process not defined error
for #199
=> fix: remove env debug flag

packages/core/shared/src/batchItem.js, packages/ui/upload-preview/types/index.test-d.tsx
=> test: add crop example to preview types check

cypress/integration/uploady/Uploady-headerFromPreSend-spec.js, package.json, packages/core/chunked-sender/package.json, packages/core/life-events/package.json, packages/core/life-events/src/tests/lifeEvents.test.js, packages/core/mock-sender/package.json, packages/core/retry/package.json, packages/core/safe-storage/package.json, packages/core/sender/package.json, packages/core/shared/package.json, packages/core/simple-state/package.json, packages/core/tus-sender/package.json, packages/core/uploader/package.json, packages/core/uploader/src/tests/utils.test.js, packages/core/uploader/src/utils.js, packages/native/native-uploady/package.json, packages/ui/chunked-uploady/package.json, packages/ui/retry-hooks/package.json, packages/ui/shared/package.json, packages/ui/shared/src/index.js, packages/ui/tus-uploady/package.json, packages/ui/upload-button/package.json, packages/ui/upload-drop-zone/package.json, packages/ui/upload-paste/package.json, packages/ui/upload-preview/package.json, packages/ui/upload-url-input/package.json, packages/ui/uploady/Uploady.stories.js, packages/ui/uploady/package.json, packages/ui/uploady/src/index.js, yarn.lock
fix for #232 
deep unwrap broken due to forced change from previous flow-bin upgrade
=> Fix bug upload deep unwrap

packages/core/tus-sender/src/tusSender/initTusUpload/createUpload.js, packages/core/tus-sender/src/tusSender/initTusUpload/tests/createUpload.test.js
=> fix(tus-sender): bug in upload url concatenate of absolute location header

packages/core/life-events/src/lifeEvents.js, packages/core/life-events/src/tests/lifeEvents.test.js, packages/ui/upload-drop-zone/src/UploadDropZone.js, packages/ui/upload-drop-zone/src/UploadDropZone.test.js
handle drag over and drag leave better so container doesnt "flicker" due to class name changes
fix for #256
=> Fix drop zone flicker

.storybook/main.js, babel.config.js, cypress/integration/retry-hooks/RetryHooks-queue-spec.js, cypress/integration/upload-button/UploadButton-progress-spec.js, packages/ui/upload-preview/README.md, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/upload-preview/src/UploadPreview.js, packages/ui/upload-preview/src/index.js, packages/ui/upload-preview/src/tests/UploadPreview.test.js, packages/ui/upload-preview/src/tests/usePreviewsLoader.test.js, packages/ui/upload-preview/src/types.js, packages/ui/upload-preview/src/usePreviewsLoader.js, packages/ui/upload-preview/types/index.d.ts, packages/ui/upload-preview/types/index.test-d.tsx, scripts/ensureTypes.js
=> feat: customize preview batch items method

cypress/integration/upload-preview/UploadPreview-progress-spec.js, package.json, packages/ui/shared/src/hooks/eventListenerHooks.js, packages/ui/shared/src/hooks/hooksUtils.js, packages/ui/shared/src/hooks/tests/hooksUtils.test.js, packages/ui/shared/src/types.js, packages/ui/shared/types/index.d.ts, packages/ui/shared/types/index.test-d.tsx, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/uploady/README.md, yarn.lock
* upgrade cypress to 9.2.0
* add spec for preview progress
=> feat: allow stateful event hooks to use scope without callback

bundle.config.js, cypress/integration/chunked-sender/ChunkedSender-Progress-spec.js, cypress/integration/upload-drop-zone/UploadDropZone-dropHandler-spec.js, cypress/integration/uploady/Uploady-autoUpload-off-spec.js, cypress/support/storyLog.js, guides/FileFilter.md, packages/core/chunked-sender/ChunkedSender.stories.js, packages/core/life-events/package.json, packages/core/life-events/src/lifeEvents.js, packages/core/shared/src/index.js, packages/core/shared/src/tests/mocks/rpldy-shared.mock.js, packages/core/shared/src/types.js, packages/core/shared/src/utils/index.js, packages/core/shared/src/utils/isPromise.js, packages/core/shared/src/utils/tests/isPromise.test.js, packages/core/shared/types/index.d.ts, packages/core/uploader/README.md, packages/core/uploader/src/batch.js, packages/core/uploader/src/defaults.js, packages/core/uploader/src/processor.js, packages/core/uploader/src/tests/batch.test.js, packages/core/uploader/src/tests/processor.test.js, packages/core/uploader/src/tests/uploader.test.js, packages/core/uploader/src/uploader.js, packages/core/uploader/types/index.d.ts, packages/core/uploader/types/index.test-d.ts
=> feat: make fileFilter support async

.storybook/uploadyPreset.js
added automation creation of GH Release + version PR
=> chore: refactor release script

cypress.json, cypress/integration/tus-uploady/TusUploady-send-data-spec.js, cypress/integration/upload-preview/UploadPreview-two-fields-spec.js, packages/ui/shared/src/hooks/eventListenerHooks.js, packages/ui/shared/types/index.d.ts, packages/ui/upload-button/UploadButton.stories.js, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/upload-preview/src/types.js
with single uploady and separate previews
- added spec for new story
- fix BatchStartHook TS type signature
- chore: remove cypress video recording
=> docs: two fields preview story

.storybook/welcome.stories.mdx, cypress/integration/dropFile.js, cypress/integration/uploadFile.js, cypress/support/commands.js, cypress/support/pasteFile.js, package.json, story-helpers/Welcome.js, yarn.lock
remove cypress-file-upload 3rd party
=> test: use new selectFile from cypress

cypress/integration/uploady/Uploady-failed-mock-spec.js, cypress/support/index.d.ts, cypress/support/storyLog.js, packages/core/mock-sender/src/mockSender.js, packages/core/mock-sender/src/tests/mockSender.test.js, packages/core/mock-sender/src/types.js, packages/core/shared/src/types.js, packages/ui/uploady/Uploady.stories.js
adds ability to init mock sender enhancer with isSuccessfulCall 
also makes mock sender use isSuccessfulCall callback from uploader options
for #348
=> Mock sender is successful call

packages/core/mock-sender/README.md
=> docs: update mock-sender readme

cypress/integration/uploady/Uploady-cancel-with-async-presend-spec.js, packages/core/uploader/src/queue/batchHelpers.js, packages/core/uploader/src/queue/itemHelpers.js, packages/core/uploader/src/queue/preSendPrepare.js, packages/core/uploader/src/queue/processBatchItems.js, packages/core/uploader/src/queue/tests/batchHelpers.test.js, packages/core/uploader/src/queue/tests/itemHelpers.test.js, packages/core/uploader/src/queue/tests/preSendPrepare.test.js, packages/core/uploader/src/queue/tests/processBatchItems.test.js, packages/core/uploader/src/queue/tests/processFinishedRequest.test.js, packages/ui/shared/src/hooks/eventListenerHooks.js, packages/ui/shared/types/index.d.ts, packages/ui/shared/types/index.test-d.tsx, packages/ui/uploady/Uploady.stories.js
handle abort of item/batch while async pre-send or batch-start hasnt returned yet
fixes #379
=> Fix abort with async prepare

cypress/integration/retry-hooks/RetryHooks-queue-spec.js, packages/core/abort/src/abort.js, packages/core/abort/src/tests/abort.test.js, packages/core/abort/src/types.js, packages/core/uploader/src/queue/processAbort.js, packages/core/uploader/src/queue/tests/processAbort.test.js
=> fix: use item queue for pmode threshold calc

cypress/integration/upload-preview/UploadPreview-multi-crop-spec.js, packages/core/retry/src/index.js, packages/core/retry/src/retry.js, packages/core/retry/src/types.js, packages/core/retry/types/index.d.ts, packages/ui/retry-hooks/src/types.js, packages/ui/retry-hooks/src/useBatchRetry.js, packages/ui/retry-hooks/src/useRetry.js, packages/ui/retry-hooks/types/index.d.ts, packages/ui/retry-hooks/types/index.test-d.tsx
=> fix: retry types

README.md
Hello everyone,
While I was checking out the Readme, I've found some minor issues and while I was at it, I thought I will simply send the PR with the fixes.
Have a nice day and thanks for your work!
=> Fix some spelling problems and typos

.storybook/VersionBadge.js, cypress/integration/dropFile.js, cypress/integration/selectFiles.js, cypress/integration/upload-drop-zone/UploadDropZone-custom-remove-spec.js, cypress/integration/upload-drop-zone/UploadDropZone-get-files-filter-spec.js, cypress/integration/upload-drop-zone/UploadDropZone-handle-only-files-spec.js, cypress/integration/upload-drop-zone/UploadDropZone-no-handle-spec.js, cypress/integration/uploadFile.js, packages/core/shared/src/index.js, packages/core/shared/src/triggerUpdater.js, packages/core/shared/src/utils/index.js, packages/core/shared/src/utils/isEmpty.js, packages/core/shared/types/index.d.ts, packages/ui/retry-hooks/src/tests/useBatchRetry.test.js, packages/ui/retry-hooks/src/tests/useRetry.test.js, packages/ui/upload-drop-zone/README.md, packages/ui/upload-drop-zone/UploadDropZone.stories.js, packages/ui/upload-drop-zone/src/UploadDropZone.js, packages/ui/upload-drop-zone/src/UploadDropZone.test.js, packages/ui/upload-drop-zone/src/types.js, packages/ui/upload-drop-zone/types/index.d.ts, packages/ui/upload-drop-zone/types/index.test-d.tsx
- provide getFiles to dropHandler
- allow control of whether to handle drag (boolean or callback)
* add isEmpty util to shared
=> upload-drop-zone improvements

packages/core/uploader/README.md, packages/ui/shared/src/types.js, packages/ui/shared/types/index.d.ts, packages/ui/shared/types/index.test-d.tsx, packages/ui/uploady/README.md, tsconfig.json
=> Fix batch add typing

cypress/integration/tus-uploady/TusUploady-retry-spec.js, cypress/integration/tus-uploady/TusUploady-simple-spec.js, packages/ui/retry-hooks/README.md, packages/ui/tus-uploady/TusUploady.stories.js, packages/ui/tus-uploady/package.json
abort TUS upload and then retry - expect upload to resume
=> test: add spec for TUS retry

cypress/integration/upload-preview/UploadPreview-multi-crop-spec.js, cypress/integration/upload-preview/UploadPreview-removePreview-spec.js, cypress/integration/upload-preview/examineCroppedUploadReq.js, packages/ui/upload-preview/README.md, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/upload-preview/src/UploadPreview.js, packages/ui/upload-preview/src/tests/UploadPreview.test.js, packages/ui/upload-preview/src/tests/usePreviewsLoader.test.js, packages/ui/upload-preview/src/types.js, packages/ui/upload-preview/src/usePreviewsLoader.js, packages/ui/upload-preview/src/utils.js, packages/ui/upload-preview/types/index.d.ts, packages/ui/upload-preview/types/index.test-d.tsx
- added to preview methods
- added to preview component props
for #448
=> feat: added removePreview

packages/core/tus-sender/src/tusSender/initTusUpload/resumeUpload.js, packages/core/tus-sender/src/tusSender/initTusUpload/tests/resumeUpload.test.js
=> fix: improved tus resume abort handling

cypress/integration/uploady/Uploady-cancel-on-add-spec.js, packages/core/uploader/src/processor.js, packages/core/uploader/src/queue/batchHelpers.js, packages/core/uploader/src/queue/tests/batchHelpers.test.js, packages/core/uploader/src/queue/tests/uploaderQueue.test.js, packages/core/uploader/src/queue/types.js, packages/core/uploader/src/queue/uploaderQueue.js, packages/core/uploader/src/tests/processor.test.js, packages/core/uploader/src/tests/uploader.test.js, packages/core/uploader/src/types.js, packages/core/uploader/src/uploader.js, packages/ui/uploady/Uploady.stories.js
=> Fix for Cancel on batch add event

.eslintrc.js, packages/ui/shared/src/uploadyVersion.js
=> fix: add globalThis to avoid error on edge runtime

.github/workflows/relesae.yml, lerna.json
have to have workflow committed to master before can run it first time
=> Release GH Workflow - initial

.storybook/main.js, bundle.config.js, packages/core/shared/src/types.js, packages/core/shared/types/index.d.ts, packages/core/uploader/src/batch.js, packages/core/uploader/src/batchItemsSender.js, packages/core/uploader/src/queue/tests/uploaderQueue.test.js, packages/core/uploader/src/queue/uploaderQueue.js, packages/ui/uploady/Uploady.stories.js, server/package.json, server/yarn.lock
=> fix: improve batch upload progress data

cypress/integration/chunked-sender/ChunkedSender-Progress-spec.js, cypress/integration/chunked-sender/ChunkedSender-error-spec.js, cypress/support/e2e.js, cypress/support/index.d.ts, cypress/support/wait.js, packages/core/chunked-sender/README.md, packages/core/chunked-sender/src/chunkedSender/getChunkedState.js, packages/core/chunked-sender/src/chunkedSender/handleChunkRequest.js, packages/core/chunked-sender/src/chunkedSender/sendChunks.js, packages/core/chunked-sender/src/chunkedSender/tests/processChunks.test.js, packages/core/chunked-sender/src/chunkedSender/tests/sendChunks.test.js, packages/core/chunked-sender/src/chunkedSender/types.js, packages/ui/chunked-uploady/types/index.test-d.tsx
=> feat: expose chunk error to item response data

package.json, packages/core/abort/package.json, packages/core/chunked-sender/package.json, packages/core/life-events/package.json, packages/core/mock-sender/package.json, packages/core/raw-uploader/package.json, packages/core/retry/package.json, packages/core/safe-storage/package.json, packages/core/sender/package.json, packages/core/shared/package.json, packages/core/simple-state/package.json, packages/core/tus-sender/package.json, packages/core/uploader/package.json, packages/native/native-uploady/package.json, packages/ui/chunked-uploady/package.json, packages/ui/retry-hooks/package.json, packages/ui/shared/package.json, packages/ui/tus-uploady/package.json, packages/ui/upload-button/package.json, packages/ui/upload-button/src/UploadButton.js, packages/ui/upload-drop-zone/package.json, packages/ui/upload-drop-zone/src/UploadDropZone.js, packages/ui/upload-paste/package.json, packages/ui/upload-preview/package.json, packages/ui/upload-url-input/package.json, packages/ui/uploady/package.json, packages/ui/uploady/src/Uploady.js, scripts/upgradeDep.js, scripts/utils.js, yarn.lock
=> Upgrade flow

packages/ui/upload-preview/README.md, packages/ui/upload-preview/UploadPreview.stories.js, packages/ui/upload-preview/src/index.js, packages/ui/upload-preview/src/tests/usePreviewsLoader.test.js, packages/ui/upload-preview/src/types.js, packages/ui/upload-preview/src/usePreviewsLoader.js, packages/ui/upload-preview/types/index.d.ts, packages/ui/upload-preview/types/index.test-d.tsx
=> Public previews loader hook

packages/core/raw-uploader/types/index.d.ts, packages/core/shared/types/index.d.ts, packages/core/uploader/types/index.d.ts, packages/ui/shared/types/index.d.ts
=> fix: improve uploady props extendability

.github/actions/bundle-size-report/index.mjs, .github/workflows/pr.yml, cypress/integration/chunked-uploady/ChunkedUploady-WithChunkEventHooks-spec.js, cypress/reporters-config.json, package.json, packages/ui/chunked-uploady/ChunkedUploady.stories.js, packages/ui/chunked-uploady/src/types.js, packages/ui/chunked-uploady/types/index.d.ts, packages/ui/chunked-uploady/types/index.test-d.tsx, pnpm-lock.yaml
=> fix: update chunk event hooks to accept promise return

packages/core/uploader/README.md, packages/ui/chunked-uploady/README.md, packages/ui/retry-hooks/README.md, packages/ui/tus-uploady/README.md, packages/ui/upload-button/README.md, packages/ui/upload-drop-zone/README.md, packages/ui/upload-paste/README.md, packages/ui/upload-preview/README.md, packages/ui/upload-url-input/README.md, packages/ui/uploady/README.md
=> docs: uploader readme

cypress/e2e-weights.json, cypress/integration/uploader/Uploader-no-prepare-pollute-spec.js, packages/core/uploader/Uploader.stories.js, packages/core/uploader/src/queue/batchHelpers.js, packages/core/uploader/src/queue/itemHelpers.js, packages/core/uploader/src/queue/preSendPrepare.js, packages/core/uploader/src/queue/tests/batchHelpers.test.js, packages/core/uploader/src/queue/tests/itemHelpers.test.js, packages/core/uploader/src/queue/tests/preSendPrepare.test.js, packages/core/uploader/src/queue/tests/processFinishedRequest.test.js, packages/core/uploader/src/queue/types.js, packages/core/uploader/src/queue/uploaderQueue.js
=> prevent pollution batch options in requestPreSend

packages/core/chunked-sender/README.md, packages/core/mock-sender/README.md, packages/core/retry/README.md, packages/core/sender/README.md, packages/core/tus-sender/README.md, packages/core/uploader/README.md, packages/native/native-uploady/README.md, packages/ui/chunked-uploady/README.md, packages/ui/retry-hooks/README.md, packages/ui/tus-uploady/README.md, packages/ui/upload-button/README.md, packages/ui/upload-drop-zone/README.md, packages/ui/upload-paste/README.md, packages/ui/upload-preview/README.md, packages/ui/upload-url-input/README.md, packages/ui/uploady/README.md
=> docs: fix internal readme links

.flowconfig, .github/actions/bundle-size-report/action.yml, bundle-size-report.json, cypress/integration/upload-drop-zone/UploadDropZone-simple-no-contain-check-spec.js, packages/ui/upload-drop-zone/UploadDropZone.stories.js, packages/ui/upload-drop-zone/package.json, packages/ui/upload-drop-zone/src/UploadDropZone.js, packages/ui/upload-drop-zone/src/UploadDropZone.test.jsx, packages/ui/upload-drop-zone/src/types.js, packages/ui/upload-drop-zone/types/index.d.ts, pnpm-lock.yaml
=> feat: Drop zone - allow full control over drag handling
